# Generated by Django 4.1.1 on 2022-09-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                (
                    "active_status",
                    models.CharField(
                        choices=[("A", "Active"), ("B", "Aspiring")], max_length=1
                    ),
                ),
                ("is_admin", models.BooleanField()),
            ],
        ),
    ]
