# Generated by Django 4.1.1 on 2022-09-17 20:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("attendance_tracker", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("date", models.DateTimeField()),
                ("duration", models.DurationField()),
            ],
        ),
        migrations.AddField(
            model_name="person",
            name="discord_id",
            field=models.CharField(
                default=datetime.datetime(
                    2022, 9, 17, 20, 48, 49, 709346, tzinfo=datetime.timezone.utc
                ),
                max_length=32,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="person",
            name="active_status",
            field=models.CharField(
                choices=[("A", "Active"), ("B", "Aspiring")], default="B", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("announcement_id", models.CharField(max_length=32)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attendance_tracker.meeting",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attendance_tracker.person",
                    ),
                ),
            ],
        ),
    ]
