# Generated by Django 4.1.1 on 2022-09-18 01:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "attendance_tracker",
            "0002_meeting_person_discord_id_alter_person_active_status_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendancerecord",
            name="announcement_id",
        ),
        migrations.RemoveField(
            model_name="person",
            name="discord_id",
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="last_updated",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="meeting",
            name="announcement_snowflake",
            field=models.CharField(default=100, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="meeting",
            name="message",
            field=models.CharField(default="false", max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="person",
            name="snowflake",
            field=models.CharField(default=123, max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
