# Generated by Django 4.1.1 on 2022-09-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance_tracker", "0003_remove_attendancerecord_announcement_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snowflake", models.CharField(max_length=32)),
                ("active_member_snowflake", models.CharField(max_length=32)),
                ("aspiring_member_snowflake", models.CharField(max_length=32)),
            ],
        ),
    ]
