# Generated by Django 4.1.1 on 2022-09-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance_tracker", "0004_guild"),
    ]

    operations = [
        migrations.AddField(
            model_name="guild",
            name="name",
            field=models.CharField(default="", max_length=64),
            preserve_default=False,
        ),
    ]
