# Generated by Django 4.1.1 on 2022-09-19 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance_tracker", "0005_guild_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="guild",
            name="announcements_channel_snowflake",
            field=models.CharField(default=728843568680009758, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="guild",
            name="attendance_channel_snowflake",
            field=models.CharField(default=955559096742989884, max_length=32),
            preserve_default=False,
        ),
    ]
